def romance_questions():
    print('|----------------------------------|')
    print('|                                  |')
    print('|             Romance              |')
    print('|                                  |')
    print('|----------------------------------|')
    print('| 1.            Question           |')
    print('|----------------------------------|')
    print('|  A.  Multiple choice             |')
    print('|----------------------------------|')
    print('|  B.   Multiple Choice            |')
    print('|----------------------------------|')
    print('|  C.   Multiple Choice            |')
    print('|----------------------------------|')

def drama_questions():
    print('|----------------------------------|')
    print('|                                  |')
    print('|             Drama                |')
    print('|                                  |')
    print('|----------------------------------|')
    print('| 1.            Question           |')
    print('|----------------------------------|')
    print('|  A.   Multiple Choice            |')
    print('|----------------------------------|')
    print('|  B.   Multiple Choice            |')
    print('|----------------------------------|')
    print('|  C.   Multiple Choice            |')
    print('|----------------------------------|')

def horror_questions():
    print('|----------------------------------|')
    print('|                                  |')
    print('|             Horror               |')
    print('|                                  |')
    print('|----------------------------------|')
    print('| 1.            Question           |')
    print('|----------------------------------|')
    print('|  A.   Multiple Choice            |')
    print('|----------------------------------|')
    print('|  B.   Multiple Choice            |')
    print('|----------------------------------|')
    print('|  C.   Multiple Choice            |')
    print('|----------------------------------|')

def action_questions():
    print('|----------------------------------|')
    print('|                                  |')
    print('|             Action               |')
    print('|                                  |')
    print('|----------------------------------|')
    print('| 1.       Question                |')
    print('|----------------------------------|')
    print('|  A.   Multiple Choice            |')
    print('|----------------------------------|')
    print('|  B.   Multiple Choice            |')
    print('|----------------------------------|')
    print('|  C.   Multiple Choice            |')
    print('|----------------------------------|')

def comedy_questions():
    print('|----------------------------------|')
    print('|                                  |')
    print('|             Comedy               |')
    print('|                                  |')
    print('|----------------------------------|')
    print('| 1.            Question           |')
    print('|----------------------------------|')
    print('|  A.   Multiple Choice            |')
    print('|----------------------------------|')
    print('|  B.   Multiple Choice            |')
    print('|----------------------------------|')
    print('|  C.   Multiple Choice            |')
    print('|----------------------------------|')

def scifi_questions():
    print('|----------------------------------|')
    print('|                                  |')
    print('|             Scifi                |')
    print('|                                  |')
    print('|----------------------------------|')
    print('| 1.            Question           |')
    print('|----------------------------------|')
    print('|  A.   Multiple Choice            |')
    print('|----------------------------------|')
    print('|  B.   Multiple Choice            |')
    print('|----------------------------------|')
    print('|  C.   Multiple Choice            |')
    print('|----------------------------------|')


