from documentation_pkg.userclass import Players, User
from documentation_pkg.animations import lost_image,winner
#from documentation_pkg.homepage import player1,player2

def romance_question_one():
    print('|----------------------------------|')
    print('|                                  |')
    print('|             Romance              |')
    print('|                                  |')
    print('|----------------------------------|')
    print('| 1.     Who was the author of     |')
    print('|             the novel            |')
    print('|           The Notebook?          |')
    print('|----------------------------------|')
    print('|  A.  Nicholas Cage               |')
    print('|----------------------------------|')
    print('|  B.   Nicholas Sparks            |')
    print('|----------------------------------|')
    print('|  C.   Jane Austin                |')
    print('|----------------------------------|')
    print()
    choice = input("| Select your answer:")
    print()
    if choice == "b":
        winner()
    else:
        lost_image()



def romance_question_two():
    print('|----------------------------------|')
    print('|                                  |')
    print('|             Romance              |')
    print('|                                  |')
    print('|----------------------------------|')
    print('| 2.     During what war was       |')
    print('|     the 1942 film Casablanca     |')
    print('|              set in?             |')
    print('|----------------------------------|')
    print('|  A.  Civil War                   |')
    print('|----------------------------------|')
    print('|  B.   World War I                |')
    print('|----------------------------------|')
    print('|  C.   World War II               |')
    print('|----------------------------------|')
    print()
    choice = input("| Select your answer:")
    if choice =="c":
        winner()
    else:
        lost_image()


def romance_question_three():
    print('|----------------------------------|')
    print('|                                  |')
    print('|             Romance              |')
    print('|                                  |')
    print('|----------------------------------|')
    print('| 3.     Who wrote the novel       |')
    print('|     Pride and Prejudice which    |')
    print('|    was the basis for the 1940    |')
    print('| and 2005 film by the same title? |')
    print('|----------------------------------|')
    print('|  A.  Jane Austen                 |')
    print('|----------------------------------|')
    print('|  B.   Jake Ryan                  |')
    print('|----------------------------------|')
    print('|  C.   Jk Rowling                 |')
    print('|----------------------------------|')
    print()
    choice = input("| Select your answer:")
    if choice == "a":
        winner()
    else:
        lost_image()

def romance_question_four():
    print('|----------------------------------|')
    print('|                                  |')
    print('|             Romance              |')
    print('|                                  |')
    print('|----------------------------------|')
    print('| 4.     What is the title         |')
    print('|     of the 2014 movie, based     |')
    print('|    on the novel by John Greene   |')
    print('|     which is about to cancer     |')
    print('|    stricken teens who meet at    |')
    print('|        a support group           |')
    print('|          and in love             |')
    print('|----------------------------------|')
    print('|  A.  The Faults in Our Stars     |')
    print('|----------------------------------|')
    print('|  B.   A walk to Remember         |')
    print('|----------------------------------|')
    print('|  C.   Love and other drugs       |')
    print('|----------------------------------|')
    print()
    choice = input("| Select your answer:")
    if choice == "a":
        winner()
    else:
        lost_image()

def romance_question_five():
    print('|----------------------------------|')
    print('|                                  |')
    print('|             Romance              |')
    print('|                                  |')
    print('|----------------------------------|')
    print('| 5.      What 1989 teen           |')
    print('|       romantic comedy was        |')
    print('|    Cameron Crowe directional     |')
    print('|             debut?               |')
    print('|----------------------------------|')
    print('|  A.  Say Anything                |')
    print('|----------------------------------|')
    print('|  B.   Sixteen Candles            |')
    print('|----------------------------------|')
    print('|  C.   Dirty Dancing              |')
    print('|----------------------------------|')
    print()
    choice = input("| Select your answer:")
    if choice =="a":
        winner()
    else:
        lost_image()

def romance_question_six():
    print('|----------------------------------|')
    print('|                                  |')
    print('|             Romance              |')
    print('|                                  |')
    print('|----------------------------------|')
    print('| 6. Based off the 50 first dates  |')
    print('|       film, what song did Lucy   |')
    print('|    sing everyday she met Henry?  |')
    print('|      Also, who was it sung by?   |')
    print('|----------------------------------|')
    print('|  A. "Love Fool" by The Cardigans |')
    print('|----------------------------------|')
    print('|  B.   "Wouldnt it be be nice"    |')
    print('|          by The Beach Boys       |')
    print('|----------------------------------|')
    print('|  C."My girl " by The Temptations |')
    print('|----------------------------------|')
    print()
    choice = input("| Select your answer:")
    if choice =="b":
        winner()
    else:
        lost_image()

# def romance_question_seven():
#     print('|----------------------------------|')
#     print('|                                  |')
#     print('|             Romance              |')
#     print('|                                  |')
#     print('|----------------------------------|')
#     print('| 3.      What 1989 teen           |')
#     print('|       romantic comedy was        |')
#     print('|    Cameron Crowe directional     |')
#     print('|             debut?               |')
#     print('|----------------------------------|')
#     print('|  A.  Say Anythin                 |')
#     print('|----------------------------------|')
#     print('|  B.   Sixteen Candles            |')
#     print('|----------------------------------|')
#     print('|  C.   Dirty Dancing              |')
#     print('|----------------------------------|')

# def romance_question_eight():
#     print('|----------------------------------|')
#     print('|                                  |')
#     print('|             Romance              |')
#     print('|                                  |')
#     print('|----------------------------------|')
#     print('| 3.      What 1989 teen           |')
#     print('|       romantic comedy was        |')
#     print('|    Cameron Crowe directional     |')
#     print('|             debut?               |')
#     print('|----------------------------------|')
#     print('|  A.  Say Anythin                 |')
#     print('|----------------------------------|')
#     print('|  B.   Sixteen Candles            |')
#     print('|----------------------------------|')
#     print('|  C.   Dirty Dancing              |')
#     print('|----------------------------------|')

# def romance_question_nine():
#     print('|----------------------------------|')
#     print('|                                  |')
#     print('|             Romance              |')
#     print('|                                  |')
#     print('|----------------------------------|')
#     print('| 3.      What 1989 teen           |')
#     print('|       romantic comedy was        |')
#     print('|    Cameron Crowe directional     |')
#     print('|             debut?               |')
#     print('|----------------------------------|')
#     print('|  A.  Say Anythin                 |')
#     print('|----------------------------------|')
#     print('|  B.   Sixteen Candles            |')
#     print('|----------------------------------|')
#     print('|  C.   Dirty Dancing              |')
#     print('|----------------------------------|')

# def romance_question_ten():
#     print('|----------------------------------|')
#     print('|                                  |')
#     print('|             Romance              |')
#     print('|                                  |')
#     print('|----------------------------------|')
#     print('| 3.      What 1989 teen           |')
#     print('|       romantic comedy was        |')
#     print('|    Cameron Crowe directional     |')
#     print('|             debut?               |')
#     print('|----------------------------------|')
#     print('|  A.  Say Anythin                 |')
#     print('|----------------------------------|')
#     print('|  B.   Sixteen Candles            |')
#     print('|----------------------------------|')
#     print('|  C.   Dirty Dancing              |')
#     print('|----------------------------------|')